%------------------------------------------------------------------------------
% File     : CSR069+5 : TPTP v9.2.1. Bugfixed v3.5.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR069+5
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.52 v9.1.0, 0.55 v9.0.0, 0.58 v7.5.0, 0.69 v7.4.0, 0.67 v7.3.0, 0.66 v7.2.0, 0.62 v7.1.0, 0.61 v7.0.0, 0.60 v6.4.0, 0.58 v6.3.0, 0.67 v6.2.0, 0.76 v6.1.0, 0.80 v6.0.0, 0.74 v5.5.0, 0.85 v5.4.0, 0.86 v5.3.0, 0.89 v5.2.0, 0.80 v5.1.0, 0.81 v5.0.0, 0.79 v4.1.0, 0.83 v4.0.0, 0.88 v3.7.0, 1.00 v3.5.0
% Syntax   : Number of formulae    : 540250 (168243 unt;   0 def)
%            Number of atoms       : 920069 (  24 equ)
%            Maximal formula atoms :    4 (   1 avg)
%            Number of connectives : 389470 (9651   ~;   0   |;15895   &)
%                                         (   0 <=>;363924  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   10 (   2 avg)
%            Maximal term depth    :    8 (   1 avg)
%            Number of predicates  : 103247 (103246 usr;   0 prp; 1-7 aty)
%            Number of functors    : 255473 (255473 usr;253178 con; 0-5 aty)
%            Number of variables   : 326597 (326597   !;   0   ?)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
% Bugfixes : v3.5.0 - Bugfixes in CSR002+4.ax
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_5,[CSR025+5,CSR026+5,CSR027+5,CSR028+5,CSR029+5,CSR030+5,CSR031+5,CSR032+5,CSR033+5,CSR034+5,CSR035+5,CSR036+5,CSR037+5,CSR038+5,CSR039+5,CSR040+5,CSR041+5,CSR042+5,CSR043+5,CSR044+5,CSR045+5,CSR046+5,CSR047+5,CSR048+5,CSR049+5,CSR050+5,CSR051+5,CSR052+5,CSR053+5,CSR054+5,CSR055+5,CSR056+5,CSR057+5,CSR058+5,CSR059+5,CSR060+5,CSR061+5,CSR062+5,CSR063+5,CSR064+5,CSR065+5,CSR066+5,CSR067+5,CSR068+5,CSR069+5,CSR070+5,CSR071+5,CSR072+5,CSR073+5,CSR074+5])
%$static(cyc_scaling_5,include('Axioms/CSR002+4.ax'))
include('Axioms/CSR002+4.ax').
%------------------------------------------------------------------------------
fof(query269,conjecture,
    ( mtvisible(c_tptpgeo_member1_mt)
   => borderson(c_georegion_l4_x38_y24,c_georegion_l4_x39_y24) ) ).

%------------------------------------------------------------------------------
